const blankLine = '   |   |   ';
console.log('this is what an empty board would look like');
console.log(blankLine);
console.log(blankLine);
console.log(blankLine);
const guessLine = ' 1 |   |  ';
const bombLine = '   | B |   ';
console.log('this is what a board with one guess on it would look like');
console.log(guessLine);
console.log(bombLine);
console.log(blankLine);
